Note about how remove unused images (bsc#1198654)
SUSE/doc-ses pull request #1017
Opened 2022-04-26 07:20 UTC by s0nea

Signed-off-by: Tatjana Dehler <tdehler@suse.com>

2022-04-26 07:27 UTC, s0nea commented
I don't know why the bot keeps adding its commit. Even though I added the change to my commit, already.

2022-04-26 07:44 UTC, tbazant requested changes
Consider my changes to streamline the flow

2022-04-26 07:44 UTC, tbazant commented on xml/upgrade-to-pacific.xml
> +</screen>
```suggestion
<screen>&prompt.smaster;salt '*' cmd.shell "podman image prune --all --force"</screen>
```

2022-04-26 07:44 UTC, tbazant commented on xml/upgrade-to-pacific.xml
> +      upgrade, run:
```suggestion
      Optionally, remove unused container images remaining on the system after the
      upgrade:
```

2022-04-26 07:44 UTC, tbazant commented on xml/upgrade-to-pacific.xml
> +     </para>
```suggestion
```

2022-04-26 07:56 UTC, s0nea commented
> Consider my changes to streamline the flow

Thank you for the review! I'll update the PR accordingly.

2022-04-26 18:08 UTC, tbazant commented on xml/upgrade-to-pacific.xml
> +<screen>&prompt.root;salt '*' cmd.shell "podman image prune --all --force"</screen>
```suggestion
<screen>&prompt.smaster;salt '*' cmd.shell "podman image prune --all --force"</screen>
```

2022-04-26 18:09 UTC, tbazant approved these changes
LGTM

2022-04-27 07:24 UTC, tbazant commented
> I don't know why the bot keeps adding its commit. Even though I added the change to my commit, already.

It's probably XML formatting webhook, just ignore it

2022-04-27 09:16 UTC, dariavladykina approved these changes
LGTM

2022-04-28 07:47 UTC, merged