Rados Gateway: Update manual resharding procedure
SUSE/doc-ses pull request #1018
Opened 2022-05-02 10:02 UTC by m-ildefons

- More detailed instruction on par with the RedHat manual
- Include warning about consequences

Fixes: bsc#1198074
Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>

2022-05-02 11:59 UTC, trociny commented
Just IMHO, but I would do it a little different.

I would leave this generic "Resharding the bucket index" section as simple as it is now, and just add a warning, that currently it does not work for multisite sync, and that multisite require full bucket resync after the shard change, see more details in multisite section (link).

And then in the "Multisite Object Gateways" [1] I would the "limitations" section, where add a note that resharding would not work and require the full resync. And in the "General Object Gateway maintenance" subsection I would describe a procedure for multisite bucket reshard.

[1] https://documentation.suse.com/ses/7.1/html/ses-all/cha-ceph-gw.html#ceph-rgw-fed
[2] https://documentation.suse.com/ses/7.1/html/ses-all/cha-ceph-gw.html#ceph-rgw-maintenance

2022-05-02 13:20 UTC, m-ildefons commented
Sounds like a good idea to me, then I can also amend the note in the "limitations" section, stating that the number of shards should be chosen carefully ahead of time according to the expected contents of the bucket. This note is currently missing.
@tbazant , if you are onboard with Mykola's suggestion, I'll update the PR.

2022-05-03 19:04 UTC, tbazant commented
> Sounds like a good idea to me, then I can also amend the note in the "limitations" section, stating that the number of shards should be chosen carefully ahead of time according to the expected contents of the bucket. This note is currently missing. @tbazant , if you are onboard with Mykola's suggestion, I'll update the PR.

@m-ildefons i'm fine with the idea, go on and update it

2022-05-05 11:48 UTC, lezare requested changes
Small typo:

`... considerable abount of time`.

Other than that LGTM.

2022-05-06 03:24 UTC, asettle commented on xml/admin_ceph_gateway.xml
> +    In a multi-site configuration resharding a bucket index is not supported.
```suggestion
    Multi-site configurations do not support resharding a bucket index.

2022-05-06 03:25 UTC, asettle commented on xml/admin_ceph_gateway.xml
> +       Resharding a bucket index is not supported in a multi-site configuration.
```suggestion
    Multi-site configurations do not support resharding a bucket index.

2022-05-06 03:25 UTC, asettle commented on xml/admin_ceph_gateway.xml
> +    As a workaround the bucket can be purged from the slave zones, resharded on
```suggestion
    As a workaround, the bucket can be purged from the slave zones, resharded on

2022-05-06 03:25 UTC, asettle commented on xml/admin_ceph_gateway.xml
> +        Disable bucket synchronization for the affected bucket
```suggestion
        Disable bucket synchronization for the affected bucket:

2022-05-06 03:26 UTC, asettle commented on xml/admin_ceph_gateway.xml
> +         Wait for synchronization to finish on all zones. Check on master and slave zones with
```suggestion
         Wait for synchronization to finish on all zones. Check on master and slave zones with
         the following command:

2022-05-06 03:26 UTC, asettle commented on xml/admin_ceph_gateway.xml
> +       Reshard the bucket index on the master zone.
```suggestion
       Reshard the bucket index on the master zone:

2022-05-06 03:26 UTC, asettle commented on xml/admin_ceph_gateway.xml
> +        Purge the bucket on all slave zones.
```suggestion
        Purge the bucket on all slave zones:

2022-05-06 03:27 UTC, asettle commented on xml/admin_ceph_gateway.xml
> +      <para>On the master zone, reenable bucket synchronization.</para>
Split the <para> tags onto the separate lines, please :)

2022-05-06 03:27 UTC, asettle reviewed
Just small things :)

2022-05-06 10:55 UTC, m-ildefons commented on xml/admin_ceph_gateway.xml
> +</screen>
Does that make a difference when rendering?

2022-05-06 12:33 UTC, asettle commented on xml/admin_ceph_gateway.xml
> +</screen>
Yep

2022-05-06 12:43 UTC, dariavladykina reviewed
Hi, just a couple of nits here. Thanks!

2022-05-06 12:43 UTC, dariavladykina commented on xml/admin_ceph_gateway.xml
> +       Depending on the bucket size this can take a considerable amount of time
```suggestion
       Depending on the bucket size, this can take a considerable amount of time
```

2022-05-06 12:43 UTC, dariavladykina commented on xml/admin_ceph_gateway.xml
> +    the master zone and then re-synchronized. Depending on the contents of the
```suggestion
    the master zone, and then re-synchronized. Depending on the contents of the
```

2022-05-06 12:43 UTC, dariavladykina commented on xml/admin_ceph_gateway.xml
> +       re-synchronization of the bucket content. Depending on the size and count
```suggestion
       re-synchronization of the bucket content. Depending on the size and number
```

2022-05-06 12:43 UTC, dariavladykina commented on xml/admin_ceph_gateway.xml
> +         Wait for synchronization to finish on all zones. Check on master and
```suggestion
         Wait for the synchronization to finish on all zones. Check on master and
```

2022-05-06 12:43 UTC, dariavladykina commented on xml/admin_ceph_gateway.xml
> +         Stop the &ogw; instances. First on all slave zones, then on the master zone too.
```suggestion
         Stop the &ogw; instances. First on all slave zones, then on the master
         zone, too.
```

2022-05-06 12:43 UTC, dariavladykina commented on xml/admin_ceph_gateway.xml
> +        On the master zone, reenable bucket synchronization.
```suggestion
        On the master zone, re-enable bucket synchronization.
```

2022-05-07 07:24 UTC, trociny approved these changes
LGTM

2022-05-09 09:14 UTC, asettle approved these changes

2022-05-18 12:04 UTC, dariavladykina reviewed
Hi, please see some small corrections.Thanks!

2022-05-18 12:04 UTC, dariavladykina commented on xml/admin_ceph_gateway.xml
> +         zone too.
```suggestion
         zone, too.
```

2022-05-18 12:50 UTC, tbazant commented
@m-ildefons Is this one ready for merging? Should I then backport it to SES7 as well, o ronly 7.1?

2022-05-20 07:48 UTC, m-ildefons commented
It's ready for merging. The customer with the original issue is on SES6 and that's also where I did the testing, so it's probably best to port it there too.

2022-05-23 07:57 UTC, merged