Configure SSH user (#479)
SUSE/doc-ses pull request #491
Opened 2020-08-26 09:16 UTC by tbazant

Adds information to optionally configure SSH user.
Closes #479

2020-08-26 12:46 UTC, asettle commented on xml/deploy_cephadm.xml
> +     optional namespace. To deploy a &ganesha;, apply the following
```suggestion
     optional namespace. To deploy &ganesha;, apply the following

2020-08-26 14:02 UTC, lproven requested changes

2020-08-26 14:02 UTC, lproven commented on xml/deploy_cephadm.xml
> +     default, a user <literal>ceph-salt</literal> is used for SSH
```suggestion
     default, a user account named <literal>ceph-salt</literal> is used for SSH
```

2020-09-03 15:25 UTC, ricardoasmarques requested changes
Since https://github.com/ceph/ceph-salt/pull/363 SSH user is no longer configurable, instead, `ceph-salt` will always create and use `cephadm` user. Can we adapt this PR accordingly?

2020-09-07 07:06 UTC, merged