Replaced `ceph-volume` calls with `cephadm ceph-volume` (#450)
SUSE/doc-ses pull request #517
Opened 2020-09-08 07:44 UTC by tbazant

Changes the invocation of `ceph-volume` to run from inside containers via `cephadm`
Closes #450

2020-09-08 07:51 UTC, smithfarm commented
This is fine as far as it goes, but I would go one step farther and, at the first instance in the Admin Guide where you mention "cephadm ceph-volume", insert a helpful, explanatory box. The text in the box should explain what happened that we are suddenly prefixing all ceph-volume calls with `cephadm `. Perhaps something as simple as this:

    NOTE: In SES7, the ceph-volume executable resides in a container, so it is not runnable directly.
    Use `cephadm` to run it by prefixing your `ceph-volume` command line with `cephadm `.

2020-09-08 07:53 UTC, tbazant commented
> This is fine as far as it goes, but I would go one step farther and, at the first instance in the Admin Guide where you mention "cephadm ceph-volume", insert a helpful, explanatory box. The text in the box should explain what happened that we are suddenly prefixing all ceph-volume calls with `cephadm `. Perhaps something as simple as this:
> 
> ```
> NOTE: In SES7, the ceph-volume executable resides in a container, so it is not runnable directly.
> Use "cephadm" to run it by prefixing your "ceph-volume" command line with "cephadm ".
> ```

@smithfarm Does this approach apply to other commands as well?

2020-09-08 07:54 UTC, smithfarm commented
> @smithfarm Does this approach apply to other commands as well?

Not that I'm aware of.

2020-09-08 08:23 UTC, tbazant commented
> > @smithfarm Does this approach apply to other commands as well?
> 
> Not that I'm aware of, but there are many, many changes in the CLI user interface between SES6 and SES7, as a consequence of the move to containers. This is just one of them.

In the admin guide, there is no `ceph-volume` command :-) they're spread across all 5 guides. So I have to include that statement in some common section

2020-09-08 08:27 UTC, smithfarm commented
Each guide is a separate, standalone book, so my suggestion would be to include the same statement in each book where the "cephadm ceph-volume" appears. It should always appear at the first instance of "cephadm ceph-volume" within the given book.

We cannot expect users to switch from book to book just to find explanatory notes.

2020-09-08 10:27 UTC, lproven approved these changes

2020-09-09 09:18 UTC, tbazant commented
> Each guide is a separate, standalone book, so my suggestion would be to include the same statement in each book where the "cephadm ceph-volume" appears. It should always appear at the first instance of "cephadm ceph-volume" within the given book.
> 
> We cannot expect readers to switch from book to book just to find explanatory notes.

@smithfarm i've added the snippet to the starting common part of each book as agreed with Alex. i cannot gues what is the first occurrence of a string as it may change in time + if a customer googles it, it may well point them to the middle of a chapter. This PR seems huge as i had to restructure and align all our books accordingly

2020-09-09 10:35 UTC, smithfarm commented on xml/MAIN.susestorage.xml
> + <xi:include href="book-ceph-windows.xml" parse="xml"/>
why is the whitespace change needed?

2020-09-09 10:37 UTC, smithfarm commented on xml/MAIN.susestorage.xml
> + <xi:include href="book-ceph-windows.xml" parse="xml"/>
oh, nvm, I see now

2020-09-09 10:44 UTC, smithfarm commented on xml/ceph_prompts.xml
> +<screen>&prompt.cephuser;cephadm ceph-volume simple scan</screen>
I'm not sure `cephadm ceph-volume`, which is a special case, is a good example. Other executables that are available only in the container image would be run using `cephadm shell`, which uses a different syntax.

Also, I don't think the wording "reside inside a running container" is correct. When the user issues a command like `cephadm ceph-volume` or `cephadm shell`, cephadm executes podman, which spawns a container from the ceph base container image. The commands actually reside inside this container image, not inside "a running container". The container doesn't actually run long enough to say something "resides" in it. But maybe I'm splitting hairs here.

Maybe @sebastian-philipp could suggest a better wording?

2020-09-09 10:45 UTC, smithfarm commented on xml/common_intro_available_doc_i.xml
> +     to deploy additional services as well. It also cover steps to upgrade to
It also covers steps (missing "s" in "covers")

2020-09-09 10:46 UTC, smithfarm commented on xml/common_intro_cephwin.xml
> +  Microsoft Windows environments and &productname; susing the Windows Driver.
"using" instead of "susing"

2020-09-09 10:48 UTC, smithfarm commented
I left some comments, but I'm afraid there's too much going on in this PR for my feeble knowledge of docbook/XML to comprehend.

2020-09-09 11:58 UTC, tbazant reviewed
2 of 3 suggestions taken into account

2020-09-09 11:58 UTC, tbazant commented on xml/MAIN.susestorage.xml
> + <xi:include href="book-ceph-windows.xml" parse="xml"/>
just n XML formatting

2020-09-09 11:58 UTC, tbazant commented on xml/common_intro_available_doc_i.xml
> +     to deploy additional services as well. It also cover steps to upgrade to
```suggestion
     to deploy additional services as well. It also covers steps to upgrade to
```

2020-09-09 11:58 UTC, tbazant commented on xml/common_intro_cephwin.xml
> +  Microsoft Windows environments and &productname; susing the Windows Driver.
```suggestion
  Microsoft Windows environments and &productname; using the Windows Driver.
```

2020-09-09 12:00 UTC, tbazant commented
> I left some comments, but I'm afraid there's too much going on in this PR for my feeble knowledge of docbook/XML to comprehend.

The structural changes are not relevant for you, the content is.

2020-09-09 12:06 UTC, lproven requested changes

2020-09-09 12:06 UTC, lproven commented on xml/ceph_prompts.xml
> +    underlying operating system, but via the <command>cephadm</command> module,
```suggestion
    underlying operating system, but instead via the <command>cephadm</command> module,
```

2020-09-09 12:06 UTC, lproven commented on xml/common_intro_available_doc_i.xml
> +     &productname; &productnumber; from the previous product version.
```suggestion
     This guide focuses on deploying a basic &ceph; cluster, and how to 
     deploy additional services. It also cover the steps for upgrading to
     &productname; &productnumber; from the previous product version.
```

2020-09-09 12:06 UTC, lproven commented on xml/common_intro_available_doc_i.xml
> +      Microsoft Windows environments and &productname; susing the Windows Driver.
```suggestion
      Microsoft Windows environments and &productname; using the Windows Driver.
```

2020-09-09 12:06 UTC, lproven commented on xml/common_intro_cephwin.xml
> +  Microsoft Windows environments and &productname; susing the Windows Driver.
```suggestion
  Microsoft Windows environments and &productname; using the Windows Driver.
```

2020-09-09 12:06 UTC, lproven commented on xml/common_intro_deploy.xml
> +  &productname; &productnumber; from the previous product version.
```suggestion
  This guide focuses on deploying a basic &ceph; cluster, and how to
  deploy additional services. It also covers the steps for upgrading to
  &productname; &productnumber; from the previous product version.
```

2020-09-09 12:06 UTC, lproven commented on xml/common_intro_rook.xml
> +  customers, it's in limited availability. Contact your SUSE sales team on how
```suggestion
  customers,: it is in <emphasis>limited availability</emphasis>. For information on how
```

2020-09-09 12:06 UTC, lproven commented on xml/common_intro_rook.xml
> +  to get nominated.
```suggestion
  to get nominated, contact your SUSE sales team.
```

2020-09-09 12:06 UTC, lproven commented on xml/common_intro_rook.xml
> +  to get nominated.
Also I suspect we should use an entity for "SUSE".

2020-09-09 12:06 UTC, lproven commented on xml/rook-contributors.xml
> +  The &ceph; and &rook; projects and their documentation is a result of the
```suggestion
  The &ceph; and &rook; projects and their documentation are the result of the
```

2020-09-10 10:14 UTC, tbazant commented on xml/ceph_prompts.xml
> +    prepend it with <command>cephadm</command>, for example:
```suggestion
    prepend it with the <command>cephadm</command> command, for example:
```

2020-09-10 10:22 UTC, tbazant commented on xml/ceph_prompts.xml
> +    Since &productname; 7, &ceph; services are running containerized. If you
```suggestion
    Starting with &productname; 7, &ceph; services are running containerized. If you
```

2020-09-10 10:26 UTC, merged