Updating light blinking docs for SES 7
SUSE/doc-ses pull request #555
Opened 2020-09-11 10:55 UTC by asettle

Closes #535

2020-09-14 06:37 UTC, tbazant requested changes
just nitpicks :-)

2020-09-14 06:37 UTC, tbazant commented on xml/bp_troubleshooting_tips.xml
> +    by which daemons, and collects health metrics about those devices in
```suggestion
    &ceph; tracks which daemons manage which hardware storage devices (HDDs, SSDs), and collects health metrics about those devices in
```

2020-09-14 06:37 UTC, tbazant commented on xml/bp_troubleshooting_tips.xml
> +    can obtain this information using the following command:
```suggestion
    The <option>DEVID</option> parameter is the device identification. You
    can obtain it by running the following command:
```

2020-09-15 05:57 UTC, tbazant approved these changes
lgtm

2020-09-16 13:13 UTC, votdev approved these changes

2020-09-16 13:14 UTC, merged