WIP: Initial upgrade docs
SUSE/doc-ses pull request #582
Opened 2020-09-17 14:23 UTC by asettle

2020-09-21 14:20 UTC, swiftgist commented
Looking at line 140 from the "Verify Steps from the Previous Upgrade" explains that if the customer has been using a custom ceph.conf that they really should convert it to the modular file sections in DeepSea.

Since this document is for SES7 and intended for the audience running SES5, the upgrade to SES6 is an intermediate step.  Using a custom ceph.conf will still work.  I think that the SES7 import step of the ceph.conf has to be sufficient so there's no need to send the customer through the exercise of separating the existing ceph.conf into Salt templates to take the resulting ceph.conf and giving it to the SES7 import step.  The original should work just as well; otherwise, the import process needs addressing.

As for the section, I suppose this section could actually say that the SES6 "convert your custom ceph.conf step" is unnecessary.

2020-09-21 14:50 UTC, asettle commented
> Looking at line 140 from the "Verify Steps from the Previous Upgrade" explains that if the customer has been using a custom ceph.conf that they really should convert it to the modular file sections in DeepSea.
> 
> Since this document is for SES7 and intended for the audience running SES5, the upgrade to SES6 is an intermediate step. Using a custom ceph.conf will still work. I think that the SES7 import step of the ceph.conf has to be sufficient so there's no need to send the customer through the exercise of separating the existing ceph.conf into Salt templates to take the resulting ceph.conf and giving it to the SES7 import step. The original should work just as well; otherwise, the import process needs addressing.
> 
> As for the section, I suppose this section could actually say that the SES6 "convert your custom ceph.conf step" is unnecessary.

For future reference, the line in question is here: https://github.com/SUSE/doc-ses/pull/582/files#diff-412ce2e0102e6f0e8ffff5124bf89becR142

2020-09-23 12:18 UTC, tbazant requested changes
a few doubts, maybe not all are relevant

2020-09-23 12:18 UTC, tbazant commented on xml/admin_ceph_upgrade.xml
>       </listitem>
not sure this is still relevant

2020-09-23 12:18 UTC, tbazant commented on xml/admin_ceph_upgrade.xml
>       </listitem>
this might not be relevant at all

2020-09-23 12:18 UTC, tbazant commented on xml/admin_ceph_upgrade.xml
> +       start using the &cephadm; orchestrator module until at least all &mgr;'s
```suggestion
       &cephsalt; and &cephadm; after.  You will <emphasis>not</emphasis> be able to
       start using the &cephadm; orchestrator module until at least all &mgr;'s
```

2020-09-23 12:18 UTC, tbazant commented on xml/admin_ceph_upgrade.xml
> +   <sect2 xml:id="upgrade-backup-config-data">
maybe referencing https://documentation.suse.com/ses/6/single-html/ses-admin/#cha-deployment-backup if it covers all needed info; if it does not, we should enhance the old version and republish it

2020-09-23 12:18 UTC, tbazant commented on xml/admin_ceph_upgrade.xml
> + <sect1 xml:id="filestore2bluestore">
SES6 doc have section on that as well, https://documentation.suse.com/ses/6/single-html/ses-deployment/#filestore2bluestore, reference sounds better

2020-09-24 10:57 UTC, tbazant approved these changes
goooood

2020-09-24 13:21 UTC, merged