Added RGW specification for SSL access (bsc#1176677)
SUSE/doc-ses pull request #684
Opened 2020-10-12 10:42 UTC by tbazant

Extends the original section on RGW deployment using YAML specs.

2020-10-12 10:48 UTC, theanalyst approved these changes

2020-10-12 13:14 UTC, asettle reviewed
Looks good! Thank you!

2020-10-12 13:14 UTC, asettle commented on xml/deploy_cephadm.xml
> +				specification:
Strange rendering?

2020-10-12 13:14 UTC, asettle commented on xml/deploy_cephadm.xml
> +    details). Then you need to enable SSL, specify a port number for SSL
```suggestion
    details). You need to enable SSL, specify a port number for SSL

2020-10-12 13:14 UTC, asettle commented on xml/deploy_cephadm.xml
> +				specification:
```suggestion
   <para>
     To enable SSL and specify the port number, include the following in your
     specification:

2020-10-12 13:14 UTC, asettle commented on xml/deploy_cephadm.xml
> +    the parser to expect a multiline string as a value:
```suggestion
    the parser to expect a multiline string as a value. For example:

2020-10-12 14:58 UTC, lproven requested changes

2020-10-12 14:58 UTC, lproven commented on xml/deploy_cephadm.xml
> +    connection, and SSL certificate and key files.
```suggestion
    connections, and the SSL certificate and key files.
```

2020-10-12 14:58 UTC, lproven commented on xml/deploy_cephadm.xml
> +    To specify the SSL certificate and key, you can paste their content directly
```suggestion
    To specify the SSL certificate and key, you can paste their contents directly
```

2020-10-12 14:58 UTC, lproven commented on xml/deploy_cephadm.xml
> +    to the YAML specification file. The pipe sign '|' at the end of line tells
```suggestion
    into the YAML specification file. The pipe sign '|' at the end of line tells
```

2020-10-12 14:58 UTC, lproven commented on xml/deploy_cephadm.xml
> +    to the YAML specification file. The pipe sign '|' at the end of line tells
```suggestion
    to the YAML specification file. The pipe sign (<literal>|</literal>) at the end of line tells
```

2020-10-12 14:58 UTC, lproven commented on xml/deploy_cephadm.xml
> +    the parser to expect a multiline string as a value:
```suggestion
    the parser to expect a multi-line string as a value:
```

2020-10-13 05:52 UTC, matthewoliver reviewed
Yup, looks great. And like how you put the other approach as a tip. Will also help people when they need to update there certs (after an expiry or whatever). I.e they'll know they can chanage it with `ceph config-key set ...`.

2020-10-13 06:26 UTC, tbazant commented on xml/deploy_cephadm.xml
> +				specification:
yes, strange, coming from such a pedantic person.....me`

2020-10-13 06:31 UTC, merged