Updating common file to contain active URLs
SUSE/doc-ses pull request #773
Opened 2020-11-19 14:58 UTC by asettle

Closes #769

2020-11-19 15:11 UTC, tomschr requested changes
Just minor things with linebreaks. Other than that it looks good. :+1:

2020-11-19 15:11 UTC, tomschr commented on xml/common_intro_available_doc.xml
> +    <citetitle>Deployment Guide</citetitle></link>
Try to add the `citetitle` without a linebreak:

```suggestion
   <link xlink:href="https://documentation.suse.com/ses/7/html/ses-all/book-storage-deployment.html"
    ><citetitle>Deployment Guide</citetitle></link>
```

2020-11-19 15:11 UTC, tomschr commented on xml/common_intro_available_doc.xml
> +    <citetitle>Administration and Operations Guide</citetitle></link>
Same here:

```suggestion
   <link xlink:href="https://documentation.suse.com/ses/html/ses-all/book-storage-admin.html"
    ><citetitle>Administration and Operations Guide</citetitle></link>
```

2020-11-19 15:11 UTC, tomschr commented on xml/common_intro_available_doc.xml
> +    <citetitle>Security Hardening Guide</citetitle></link>
```suggestion
   <link xlink:href="https://documentation.suse.com/ses/html/ses-all/book-storage-security.html"
    ><citetitle>Security Hardening Guide</citetitle></link>
```

2020-11-19 15:11 UTC, tomschr commented on xml/common_intro_available_doc.xml
> +    <citetitle>Troubleshooting Guide</citetitle></link>
```suggestion
   <link xlink:href="https://documentation.suse.com/ses/html/ses-all/book-storage-troubleshooting.html"
    ><citetitle>Troubleshooting Guide</citetitle></link>
```

2020-11-19 15:11 UTC, tomschr commented on xml/common_intro_available_doc.xml
> +    <citetitle>&productname; for Windows Guide</citetitle></link>
```suggestion
   <link xlink:href="https://documentation.suse.com/ses/html/ses-all/book-storage-windows.html"
    ><citetitle>&productname; for Windows Guide</citetitle></link>
```

2020-11-19 15:15 UTC, asettle commented
Thanks @tomschr somehow I missed those breaks in my editor :)

2020-11-19 15:18 UTC, tomschr commented
No problem. It could (potentially) lead to spurious whitespaces in the link (which we should avoid).

2020-11-19 18:11 UTC, lproven approved these changes

2020-11-23 07:21 UTC, tbazant commented on xml/common_intro_available_doc.xml
>       This guide describes the integration, installation and configuration of
```suggestion
     This guide describes the integration, installation, and configuration of
```

2020-11-23 07:22 UTC, tbazant approved these changes
looks good

2020-11-23 10:35 UTC, merged