Failure to add new cluster hosts
SUSE/doc-ses pull request #812
Opened 2020-12-01 13:36 UTC by tbazant

Closes #809 
Rendered version is attaached 
[bp-troubleshooting-adding-hosts_color_en.pdf](https://github.com/SUSE/doc-ses/files/5622903/bp-troubleshooting-adding-hosts_color_en.pdf)

2020-12-01 13:40 UTC, asettle reviewed
nits

2020-12-01 13:40 UTC, asettle commented on xml/bp_troubleshooting_cephadm.xml
> +  <title>Adding Hosts with &cephadm; Fails</title>
```suggestion
  <title>Failure When Adding Hosts with &cephadm;</title>

2020-12-01 13:40 UTC, asettle commented on xml/bp_troubleshooting_cephadm.xml
> +   </screen>
Indentation is weird here?

2020-12-01 13:49 UTC, lproven approved these changes

2020-12-01 13:51 UTC, lproven requested changes

2020-12-01 13:51 UTC, lproven commented on xml/bp_troubleshooting_cephadm.xml
> +   can diagnose the reason of failure. The failure message has the following
```suggestion
   can diagnose the reason for failure. The failure message has the following
```

2020-12-01 13:51 UTC, lproven commented on xml/bp_troubleshooting_cephadm.xml
> +   If any of the previous two commands succeed, &cephsalt; is probably causing
```suggestion
   If either of the previous two commands succeed, &cephsalt; is probably causing
```

2020-12-01 13:51 UTC, lproven commented on xml/bp_troubleshooting_cephadm.xml
> +   If this succeeds, the cluster does not have a proper name resolution. Refer
```suggestion
   If this succeeds, the cluster does not have proper name resolution. Refer
```

2020-12-01 13:57 UTC, tbazant commented on xml/bp_troubleshooting_cephadm.xml
> +   </screen>
```suggestion
<screen>
&prompt.cephuser;ceph orch host add node5.example.com
Failed to connect to node5 (node5.example.com).
</screen>
```

2020-12-02 12:03 UTC, lproven approved these changes

2020-12-03 09:46 UTC, sebastian-philipp commented
The PTF change looks unrelated to this PR.

2020-12-03 12:21 UTC, merged