Improve ses6 upgrade chapter (#843)
SUSE/doc-ses pull request #859
Opened 2021-01-12 09:23 UTC by tbazant

closes #843

2021-01-12 15:57 UTC, lproven requested changes

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +<screen>/srv/salt/ceph/configuration/files/ceph.conf.d/</screen>
Ditto

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +<screen>/srv/salt/ceph/configuration/files/ceph.conf.d/</screen>
Ditto

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +<screen>/srv/pillar/ceph/proposals/config/stack/default/ceph/cluster.yml</screen>
Ditto

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +       from <filename>ceph.conf.import</filename> and remove the
**If** I understand this correctly, would it be clearer to also say "and do not remove the blah option"?

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      the cluster uses the new bucket type <literal>straw2</literal> and that
```suggestion
      the cluster uses the new bucket type <literal>straw2</literal>, and that
```

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    starting the upgrade:
Do we want the product-number to be a self-updating thing? It seems to me that a literal product number would be preferable here, but I could be wrong.

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    longer allowed and MDS daemons will refuse to start. You can check whether
```suggestion
    From &productname; &productnumber;, MDS names are no longer allowed to begin with a
    digit, and such names will cause MDS daemons to refuse to start. You can check whether
```

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    If you see the above message, the MDS names will need to be migrated before
```suggestion
    If you see the above message, the MDS names must be migrated before
```

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    will be able to access &cephfs; only after a short pause to failover.
```suggestion
    will be able to access &cephfs; only after a short pause for failover to happen.
```

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    will be able to access &cephfs; only after a short pause to failover.
This is only a suggestion -- I am not 100% what was meant.

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    Therefore plan the migration for times when you expect little or no
Surely "for a time" would make more sense?

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +       'HEALTH_OK'. If not, resolve the problem before possible reboots in next
```suggestion
       'HEALTH_OK'. If not, resolve the problem before any possible reboots in
       the next
```

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      disk space with <command>df -h</command>. When needed, free disk space by
```suggestion
      disk space with <command>df -h</command>. When needed, free up additional disk space by
```

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      until having freed enough disk space.
```suggestion
      until you have freed enough disk space.
```

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> + </screen>
```suggestion
<screen>&prompt.smaster; salt-run rebuild.node <replaceable>TARGET</replaceable>/screen>
```

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +  <title>Per Node Upgrade Instructions</title>
```suggestion
  <title>Per-Node Upgrade Instructions</title>
```

2021-01-12 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +  <title>Per Node Upgrade Instructions</title>
Also see my earlier comment about sentence case.

2021-01-12 16:45 UTC, lproven requested changes

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +   that are better allocated to tuning storage related daemons. We recommend a
```suggestion
   that would be better allocated to tuning storage-related daemons. We recommend a
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    to saturate the line.
```suggestion
    To perform <command>iperf3</command> tests for network performance,
    consider increasing the window size (with the <option>-w</option> option)
    and running multiple streams to fully test the bandwidth capability. If using
    the standard MTU, your NICs should be capable of running at approximately
    70-80% of the advertised bandwidth. If you move up to jumbo frames, the
    NIC should be able to saturate the link.
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    appropriate CPU clock speeds and settings.
```suggestion
    This is not necessarily true for faster topologies such as 100&nbsp;Gb. In
    those topologies, saturating the NIC can require substantial OS and driver
    tuning, in combination with ensuring the hardware has the appropriate
    CPU clock speeds and settings.
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    length to higher than the default 128k, resulting in slightly higher
```suggestion
    length to higher than the default 128&nbsp;kB, resulting in slightly higher
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    beyond the scope of this document.
```suggestion
    Use <command>fio</command> to test individual storage devices to understand
    the per-device performance maxima. Do this for all devices to ensure that none
    are out of specification, or are connected to expanders which lower
    bandwidth. Doing an exhaustive study of different I/O sizes and patterns
    would provide the most information about performance expectations, but is
    beyond the scope of this document.
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    sequential 64&nbsp;kB and 1&nbsp;MB. This gives a reasonable overall view
```suggestion
    sequential 64&nbsp;kB and 1&nbsp;MB buffers. This should give a reasonable overall view
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    performance measurements are made, helping to ensure that performance
```suggestion
    performance measurements are made. This helps to ensure that performance
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    devices across multiple controllers. This is simulating the node under
```suggestion
    devices across multiple controllers. This simulates the node under
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    We recommend to use the same I/O patterns and block sizes that the
```suggestion
    We recommend using the same I/O patterns and block sizes that the
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    the total number of devices in the system to allow for even distribution
```suggestion
    the total number of devices in the system, to allow for even distribution
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +     continue to rise. The inverse may also be true where a change affects
```suggestion
     continue to rise. The inverse may also be true, where a change affects
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +     until the latency average is maintained.
```suggestion
     The settings above cause <command>fio</command> to increase the I/O queue
     depth until 1% or more of IOPS no longer maintain a 10&nbsp;ms average during
     a sliding five-second window. It then backs down the queue depth until the
     latency average is maintained.
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +   hardware vendors.
```suggestion
   There are several aspects of the kernel that can be tuned on both the
   cluster and some of the clients. It is important to understand that most
   tuning is about gaining very small incremental improvements, which in
   aggregate represent a measureable (and hopefully meaningful) improvement in
   performance. For this document, information on tuning comes from a variety of
   sources. The primary source is
   <link xlink:href="https://documentation.suse.com/sles/15-SP1/html/SLES-all/book-sle-tuning.html"/>.
   We also used numerous other references, including documentation from
   hardware vendors.
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    One key area of kernel for performance tuning is to disable the
```suggestion
    One key area of kernel performance tuning is to disable its
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    side-channel attack mitigations present in the kernel. The bulk of the
```suggestion
    side-channel attack mitigations. The bulk of the
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    benefits from this tuning occur with smaller I/Os ranging in size from
```suggestion
    benefits from this occur with smaller I/Os, ranging in size from
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    implications as they involve disabling mitigations for side-channel attacks
```suggestion
    implications, as they involve disabling mitigations for side-channel attacks
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    newer processors. Evaluate carefully whether this is something needed for
```suggestion
    newer processors. You must carefully evaluate whether this is something needed for
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    the particular hardware being utilized. In the test configuration, a salt
```suggestion
    the particular hardware being utilized. In the test configuration, a &salt;
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    The first aspect to tune is to ensure that I/O if flowing in the most
```suggestion
    The first aspect to tune is to ensure that I/O is flowing in the most
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    optimal pattern. For the test cluster used in this test, that means enable
```suggestion
    optimal pattern. For the test cluster used in this test, that means enabling
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    parameter as found in the Section 12.4
```suggestion
    parameter, as found in Section 12.4
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    those such as NVMe and SSD that can service large numbers of requests.
```suggestion
    This is not an action that should be taken unilaterally on clusters which
    contain spinning media devices, due to potential performance degradation for
    those devices. The general result is that there multiple I/O queues are
    assigned to each device, allowing more jobs to be handled simultaneously by
    those device that can service large numbers of requests, such as  SSD and 
    NVMe drives.
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    differences in performance compared to the baseline.
```suggestion
    Before tuning, it is important to check and record the default values, and
    measure any differences in performance compared to that baseline.
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    2&nbsp;MB.
```suggestion
    By placing the following file in <filename>/etc/udev/rules.d</filename>,
    devices will be detected according to the model name shown in
    <filename>/sys/block/{devname}/device/model</filename>, and instructed to
    disable write caching and set the <option>read_ahead_kb</option> option to
    2&nbsp;MB.
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    2&nbsp;MB.
I note that no filename seems to be specified here. I think we should at least offer an example filename.

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    Proper tuning of the network stack can substantially add to improving the
```suggestion
    Proper tuning of the network stack can substantially assist improving the
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    The first and most impactful tuning is to utilize jumbo frame packets. For
```suggestion
    The first change, and one with the highest impact, is to utilize jumbo frame packets. For
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    this to be done, all interfaces utilizing the cluster must be set to the
This sounds strange to me.

Would "all interfaces used in the cluster" be better?

If it does not refer to internal comms between cluster nodes, then:

"all interfaces used to access the cluster"... but this seems less likely to me.

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +    creating them.
```suggestion
    this to be done, all interfaces utilizing the cluster must be set to use an MTU of
    9000 bytes. Network switches are often set to use 9100 or higher. This is 
    suitable, as they are only passing packets, not creating them.
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +      needs to only be done only in conjunction with the conditions and
```suggestion
      must only be done in conjunction with the conditions and
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +      needs to only be done only in conjunction with the conditions and
Too many "only"s!

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +      transmit (TX) buffers that is not optimal for high-throughput scenarios
```suggestion
      transmit (TX) buffers that is not optimal for high-throughput scenarios,
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +      the following command:
```suggestion
      Here we can see that the NIC can allocate buffers of up to 8&nbsp;kB,
      but it iscurrently using ones of only 1&nbsp;kB. To adjust this for the cluster, issue
      the following command:
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +     in a salt command to allow testing and validation in your environment
```suggestion
     in a &salt; command to allow testing and validation in your environment
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +      with this setting at both <literal>0</literal> and <literal>1</literal>.
```suggestion
      with setting this to both <literal>0</literal> and <literal>1</literal>.
```

2021-01-12 16:45 UTC, lproven commented on xml/tuning-os-tuning.xml
> +      help ensure that packet sequence could be better tracked:
```suggestion
      help ensure that packet sequence could be tracked better:
```

2021-01-13 12:04 UTC, tbazant reviewed
suggestions accepted

2021-01-13 12:16 UTC, tbazant commented on xml/tuning-os-tuning.xml
> +    this to be done, all interfaces utilizing the cluster must be set to the
```suggestion
    this to be done, all interfaces used in the cluster must be set to the
```

2021-01-13 16:32 UTC, smithfarm approved these changes
While reviewing this I found an additional problem, but it's not serious and I don't want to delay merge of this PR, so I'll open a new issue for it.

Looks good to me, and thanks @tbazant for doing the heavy lifting here.

2021-01-13 16:32 UTC, smithfarm commented
Do we need to be concerned about the failed Travis CI builds?

2021-01-14 17:26 UTC, lproven approved these changes

2021-01-27 10:15 UTC, merged