Apply RGW specification before restartinthe gatewayit (#864)
SUSE/doc-ses pull request #877
Opened 2021-02-01 12:58 UTC by tbazant

closes #864

2021-02-01 13:15 UTC, theanalyst approved these changes

2021-02-01 13:16 UTC, theanalyst commented on xml/admin_ceph_upgrade.xml
> +    describe in <xref linkend="deploy-cephadm-day2-service-ogw"/>, apply it,
described?

2021-02-01 13:19 UTC, lproven requested changes

2021-02-01 13:19 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    describe in <xref linkend="deploy-cephadm-day2-service-ogw"/>, apply it,
```suggestion
    described in <xref linkend="deploy-cephadm-day2-service-ogw"/>, apply it,
```

2021-02-02 09:28 UTC, tbazant commented on xml/admin_ceph_upgrade.xml
> +    describe in <xref linkend="deploy-cephadm-day2-service-ogw"/>, apply it,
yes!

2021-02-02 09:28 UTC, merged