Removed unnecessary  'PG_NUM' option (#848)
SUSE/doc-ses pull request #884
Opened 2021-02-15 12:49 UTC by tbazant

closes #848

2021-02-15 13:47 UTC, asettle approved these changes

2021-02-16 12:24 UTC, lproven requested changes

2021-02-16 12:24 UTC, lproven commented on xml/admin_operating_monitor.xml
>        collocates some PGs on the same sets of OSDs, mitigating some of the
```suggestion
      co-locates some PGs on the same sets of OSDs, mitigating some of the
```

2021-02-16 12:24 UTC, lproven commented on xml/bp_troubleshooting_status.xml
> +     The human readable description of the error may be obscurely worded if the
```suggestion
     The human-readable description of the error may be obscurely worded if the
```

2021-02-16 12:24 UTC, lproven commented on xml/bp_troubleshooting_status.xml
> +     means an unhandled exception was raised from the module’s serve function.
```suggestion
     means an unhandled exception was raised from the module’s <literal>serve</literal> function.
```

2021-02-16 12:24 UTC, lproven commented on xml/bp_troubleshooting_status.xml
> +     means an unhandled exception was raised from the module’s serve function.
"Serve function" is not a thing, and one of the only places the phrase occurs on the WWW is in our docs. 

The upstream docs contain this reference: https://docs.ceph.com/en/latest/rados/operations/health-checks/

Therefore, I think the term needs to be emphasized or something to indicate we are restricting our mention of a function to one specific one.

2021-02-16 12:24 UTC, lproven commented on xml/admin_ceph_datamgm.xml
> +    The object’s contents within a placement group are stored in a set of OSDs.
The curly quote here _is_ **technically** correct but I think we should leave smart quotation marks up to DAPS. I suggest a global search-and-replace with simple straight quotation marks or apostrophes – that is, ['] and not the back-tick [`].

2021-02-16 12:24 UTC, lproven commented on xml/bp_troubleshooting_status.xml
> +     or in combination with other pools’ actual usage). This can indicate that
Another curly apostophe here.

2021-02-16 12:24 UTC, lproven commented on xml/bp_troubleshooting_status.xml
> +     the <option>target_size_ratio</option> value for the pool is too large and
```suggestion
     the <option>target_size_ratio</option> value for the pool is too large, and
```

2021-02-17 09:08 UTC, tbazant reviewed
minor update

2021-02-17 09:08 UTC, tbazant commented on xml/admin_ceph_datamgm.xml
> +    The object’s contents within a placement group are stored in a set of OSDs.
```suggestion
    The object's contents within a placement group are stored in a set of OSDs.
```

2021-02-17 13:34 UTC, lproven approved these changes

2021-02-22 13:50 UTC, jan--f requested changes
LGTM once the erroneous note is removed

2021-02-22 13:50 UTC, jan--f commented on xml/admin_ceph_datamgm.xml
> +    groups, run the following:
This is no longer true. Since iirc `nautilus` ceph can merge PGs, aka reduce a pg_num. Feel free to just remove these last two sentences.

2021-02-23 07:50 UTC, tbazant commented on xml/admin_ceph_datamgm.xml
> +    groups, run the following:
```suggestion
    linkend="ceph-pools-operate-add-pool"/>). Once you have set
    placement groups for a pool, you may increase the number of placement
    groups by running the following command:
```

2021-02-23 07:52 UTC, merged