Update admin_monitoring_alerting.xml
SUSE/doc-ses pull request #888
Opened 2021-02-19 14:52 UTC by p-se

Add section about newly added GRAFANA_FRONTEND_API_URL to be able to
configure Grafana so that it can be reached when the Grafana users are
in a different DNS zone than the Ceph Dashboard back-end.

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1176390

Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

2021-02-22 11:23 UTC, tbazant approved these changes
LGTM

2021-02-22 16:24 UTC, lproven requested changes

2021-02-22 16:24 UTC, lproven commented on xml/admin_monitoring_alerting.xml
> +  has been configured before &grafana; has been deployed.
As lines in between have been removed, I cannot make a `suggestion`. So:

This specifies  what happens before the conditions that might cause it to happen. That is not ideal.

I suggest:

«
If no custom certificate has been configured before &grafana; has been deployed,
then a self-signed certificate is automatically created and configured for &grafana;.
»

2021-02-22 16:24 UTC, lproven commented on xml/admin_monitoring_alerting.xml
> +        The backend (Ceph Mgr module) needs to verify the existence of the
```suggestion
        The backend (Ceph MGR module) needs to verify the existence of the
```

2021-02-22 16:24 UTC, lproven commented on xml/admin_monitoring_alerting.xml
> +        The backend (Ceph Mgr module) needs to verify the existence of the
As per comment to previous PR: I think there should be an entity for Ceph...?

2021-02-22 16:24 UTC, lproven commented on xml/admin_monitoring_alerting.xml
> +        browser using an iframe. The &grafana; instance is accessed directly
```suggestion
        browser using an <literal>iframe</literal>. The &grafana; instance is accessed directly
```

2021-02-23 14:13 UTC, lproven approved these changes

2021-03-01 10:57 UTC, merged