Updated to troubleshooting guide from upstream docs (#885)
SUSE/doc-ses pull request #891
Opened 2021-02-24 09:01 UTC by tbazant

closes #885

2021-02-24 12:05 UTC, lproven requested changes

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +   In case the &mon;s cannot form a quorum, &cephadm; is not able to manage the
```suggestion
   If the &mon;s cannot form a quorum, &cephadm; will not be able to manage the
```

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +   cluster until the quorum is restored. In order to restore the MON quorum,
```suggestion
   cluster until the quorum is restored. In order to restore the &mon; quorum,
```

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +   cluster until the quorum is restored. In order to restore the MON quorum,
Entity here is only a suggestion

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +   remove unhealthy MONs form the monmap by following these steps:
Ditto

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +     Stop all MONs. Log in to each MON host via SSH and run the following
Ditto

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +     <literal>mon.c</literal> where only <literal>mon.a</literal> will survive,
**will** survive or already **is** surviving? I am not sure of the intention here.

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +    You may wish to archive the removed monitors' data directory in
```suggestion
    You may wish to archive the removed monitors' data directories from
```

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +    problems, check the problematic monitor’s <literal>mon_status</literal> via
```suggestion
    problems, check the problematic monitor's <literal>mon_status</literal> via
```

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +    believes to be in quorum, while the remaining cluster is sure it is not; or
```suggestion
    believes itself to be in the quorum, while the remaining cluster is sure it is not; or
```

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +    check <command>ceph -s</command> again just to make sure. Continue if the
```suggestion
    maybe it got into the quorum while we were troubleshooting the monitor.
    Check using <command>ceph -s</command> again, just to make sure. Continue if the
```

2021-02-24 12:05 UTC, lproven commented on xml/bp_troubleshooting_monitors.xml
> +      If you have no quorum, use the monitor’s admin socket and directly adjust
```suggestion
      If you have no quorum, use the monitor's admin socket and directly adjust
```

2021-02-26 13:06 UTC, jecluis approved these changes

2021-03-01 10:35 UTC, tbazant commented on xml/bp_troubleshooting_cephadm.xml
> +   <literal>unmanaged: true</literal> to its specification and apply it, for
```suggestion
   <literal>unmanaged: true</literal> to its specification file and apply it, for
```

2021-03-01 10:35 UTC, tbazant commented on xml/bp_troubleshooting_logging.xml
> +   In order to simplify debugging deployments of failed daemons, &cephadm;
```suggestion
   In order to simplify debugging failed daemon deployments, &cephadm;
```

2021-03-01 10:35 UTC, tbazant commented on xml/bp_troubleshooting_monitors.xml
> +   remove unhealthy MONs form the monmap by following these steps:
```suggestion
   remove unhealthy &mon;s form the monmap by following these steps:
```

2021-03-01 10:35 UTC, tbazant commented on xml/bp_troubleshooting_monitors.xml
> +     Stop all MONs. Log in to each MON host via SSH and run the following
```suggestion
     Stop all &mon;s. Log in to each &mon; host via SSH and run the following
```

2021-03-01 10:35 UTC, tbazant commented on xml/bp_troubleshooting_monitors.xml
> +     <literal>mon.c</literal> where only <literal>mon.a</literal> will survive,
```suggestion
     <literal>mon.c</literal> where only <literal>mon.a</literal> is surviving,
```

2021-03-01 10:49 UTC, merged