Add more detail to Upgrading NFS Ganesha section
SUSE/doc-ses pull request #898
Opened 2021-02-26 12:00 UTC by tserong

Fixes: https://github.com/SUSE/doc-ses/issues/872
Signed-off-by: Tim Serong <tserong@suse.com>

2021-02-26 15:45 UTC, lproven requested changes

2021-02-26 15:45 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      Repeat these steps for each &ganesha; node. You don't need to create a separate
```suggestion
      Repeat these steps for each &ganesha; node. You do not need to create a separate
```

2021-02-26 15:45 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      service specification for each node, it's enough to add each node's hostname to
```suggestion
      service specification for each node. It is sufficient to add each node's hostname to
```

2021-02-26 21:40 UTC, mgfritch approved these changes
thanks for catching this! looks like some of my incorrect dev notes somehow landed in the product doc ;)

lgtm, minus the suggestions from @lproven

2021-03-01 11:01 UTC, tbazant approved these changes
great work with docbook :-)

2021-03-01 11:01 UTC, merged