Revise adoption of monitoring services
SUSE/doc-ses pull request #922
Opened 2021-04-15 14:35 UTC by p-se

Revise monitoring adoption section

- Add docs about how to set Node-Exporter image in cephadm for local registry.
- Be more clear about having to remove the Node-Exporter service from all nodes.
- Add a command to remove Node-Exporter from all nodes at once with Salt.
- Other text revisions.

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1181301

Signed-off-by: Patrick Seidensal <pseidensal@suse.com>

2021-04-16 15:57 UTC, lproven requested changes

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +   instructions if you want to deploy &productname; on the &caasp;.
```suggestion
   instructions if you want to deploy &productname; on &caasp;.
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +   instructions if you want to deploy &productname; on the &caasp;.
I think we do not usually use articles with product names like this.

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +   &prevproductnumber; and then follow the steps in this chapter.
```suggestion
   supported. First, you must upgrade to the latest version of &productname;
   &prevproductnumber;, and then follow the steps in this chapter.
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      <emphasis>Read the release notes</emphasis> - there you can find
```suggestion
      <emphasis>Read the release notes</emphasis>. In them, you can find
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      &cephsalt; and &cephadm; after. You will <emphasis>not</emphasis> be able
```suggestion
      You need to upgrade the &smaster; first, then replace &deepsea; with
      &cephsalt; and &cephadm;. You will <emphasis>not</emphasis> be able
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      &mgr;'s are upgraded.
```suggestion
      &mgr; nodes are upgraded.
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      to happen all in one step. This means upgrade an entire node at a time,
```suggestion
      to happen in a single step. This means upgrading an entire node at a time,
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +         are down for the least amount of time possible. This is the duration
```suggestion
         are down for the shortest possible time. This is the duration
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +        upgrade from &prevcephos; to &cephos; and again briefly when each
```suggestion
        upgrade from &prevcephos; to &cephos;, and again briefly when each
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +        service is redeployed in containerized mode.
```suggestion
        service is redeployed on the containerized mode.
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    starting your upgrade to &productname; &productnumber;. For instruction on
```suggestion
    starting your upgrade to &productname; &productnumber;. For instructions on
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    &deepsea;'s default <filename>ceph.conf</filename> which is compiled from
```suggestion
    &deepsea;'s default <filename>ceph.conf</filename>, which is compiled from
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    images.
```suggestion
    Verify that each cluster node has access to the &cephos; and &productname;
    &productnumber; software repositories, as well as the registry of container
    images.
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +     configured registry, inform &ceph; which container image to use by running
```suggestion
     from <literal>registry.suse.com</literal> but rather the
     locally-configured registry, inform &ceph; which container image to use by
     running
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      deployments) or with services deployed with mixed versions.
```suggestion
      end up being unable to deploy services (in the case of air-gapped
      deployments), or with services deployed with mixed versions.
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    Before attempting any migration, we strongly recommend to make a copy of
```suggestion
    Before attempting any migration, we strongly recommend making a copy of
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +    On a per node basis, an existing &ganesha; service needs to be stopped and
```suggestion
    On a per-node basis, any existing &ganesha; service needs to be stopped and
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      For more information on creating a placement specification see
```suggestion
      For more information on creating a placement specification, see
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      happen. The default in &productname; &productnumber; is the
```suggestion
      happen. The default in &productname; &productnumber; is that the
```

2021-04-16 15:57 UTC, lproven commented on xml/admin_ceph_upgrade.xml
> +      for new pools and PGs will actually autoscale. The upgrade process does
```suggestion
      for new pools, and PGs will actually autoscale. The upgrade process does
```

2021-04-19 15:11 UTC, p-se commented
@lproven thanks for the thorough review!

2021-04-22 08:48 UTC, tbazant approved these changes
looks good

2021-04-22 08:55 UTC, tbazant commented
@p-se as the PR is almost unreadable due to different formatting of the source and target file, i've reformatted the source in SUSE:main to line-break at 80 chars, mayeb you can rebase from that to make the PR more readable?

2021-04-23 13:38 UTC, lproven approved these changes

2021-04-26 14:24 UTC, lproven approved these changes

2021-04-28 12:12 UTC, merged