Operating NFS service,  manual NFS export
SUSE/doc-ses pull request #927
Opened 2021-04-23 09:35 UTC by tbazant

This update improves the understand of what the Ganesha service does not and how to manually create an NFS export

Closes #767  
Closes #765

2021-04-23 09:39 UTC, asettle commented on xml/admin_nfsganesha.xml
> +    Operating the &ganesha; service does not export a &cephfs; file system. To
```suggestion
    The operation the &ganesha; service does not automatically export a &cephfs; file system. To

2021-04-23 09:39 UTC, asettle commented on xml/admin_nfsganesha.xml
> +    Operating the &ganesha; service does not export a &cephfs; file system. To
Is that what you mean?

2021-04-23 09:39 UTC, asettle commented on xml/admin_nfsganesha.xml
> +   To create an NFS export manually, you first need to create a configuration
```suggestion
   To create an NFS export manually, create a configuration

2021-04-23 09:40 UTC, asettle reviewed
Just comments, the first sentence is a bit odd to me?

2021-04-23 11:36 UTC, tbazant commented on xml/admin_nfsganesha.xml
> +    Operating the &ganesha; service does not export a &cephfs; file system. To
```suggestion
    Starting the &ganesha; service does not automatically export a &cephfs; file system. To
```

2021-04-23 11:40 UTC, tbazant reviewed
minor update

2021-04-23 11:40 UTC, tbazant commented on xml/admin_nfsganesha.xml
> +    export a &cephfs; file system, you first need to create an export
```suggestion
    export a &cephfs; file system, create an export
```

2021-04-23 12:26 UTC, lproven requested changes

2021-04-23 12:26 UTC, lproven commented on xml/admin_nfsganesha.xml
> +    After the export file is created and saved on the file system, run the
```suggestion
    After you have created and saved the configuration file for the new export,
    run the
```

2021-04-23 12:26 UTC, lproven commented on xml/admin_nfsganesha.xml
> +    After the export file is created and saved on the file system, run the
Reword to avoid passive voice.

2021-04-23 12:27 UTC, lproven approved these changes

2021-04-23 12:29 UTC, lproven requested changes
I see 2 or more batches of changes. I didn't realise that requesting changes in 1, then approving another change, would approve them all. Sorry.

2021-04-23 13:37 UTC, lproven approved these changes

2021-04-26 14:11 UTC, lproven requested changes

2021-04-26 14:11 UTC, lproven commented on xml/admin_nfsganesha.xml
> +   file for the export. For example, the file <filename>/tmp/export-1</filename>
```suggestion
   file for the export. For example, a file <filename>/tmp/export-1</filename>
```

2021-04-26 14:11 UTC, lproven commented on xml/admin_nfsganesha.xml
> +    following command to create the export:
```suggestion
    After you have created and saved the configuration file for the new export,
    run the following command to create the export:
```

2021-04-26 14:11 UTC, lproven commented on xml/admin_nfsganesha.xml
> +     The FSAL block should be modified to include the desired cephx user ID and
```suggestion
     The FSAL block should be modified to include the desired &cephx; user ID and
```

2021-04-28 15:03 UTC, lproven approved these changes

2021-05-04 07:32 UTC, callithea approved these changes
Lgtm

2021-05-04 07:39 UTC, merged