Adding exceptions for self-signed SSL certificates in the Ceph Dashboard
SUSE/doc-ses pull request #998
Opened 2022-03-15 10:53 UTC by votdev

Signed-off-by: Volker Theile <vtheile@suse.com>

2022-03-15 11:23 UTC, tbazant commented on xml/bp_troubleshooting_dashboard.xml
> +   the &dashboard; page to see the embedded Grafana pages.
```suggestion
   The Web browser will show an error page when accessing embedded &grafana; pages
   that are using self-signed SSL certificates. Most browsers will not show the
   button to add an exception for those pages. Instead, you need to open
   the frame in a separate browser tab to add an exception. In Firefox, for example, open
   the context menu by clicking the right mouse button and select the menu
   <menuchoice><guimenu>This Frame</guimenu> <guimenu>Open Frame in New Tab</guimenu</menuchoice>. In the new opened
   browser tab, press the <guimenu>Advanced</guimenu> button followed by the
   <guimenu>Accept the risk and continue</guimenu> button. Finally, reload
   the &dashboard; page to see the embedded &grafana; pages.
```

2022-03-15 11:24 UTC, tbazant requested changes
Small update.

2022-03-15 11:25 UTC, tbazant commented
@votdev BTW should this be backported to SES 7 as well? If yes, add `backport to SES7` label please.

2022-03-16 13:45 UTC, dariavladykina reviewed
Hi, please take a look at a minor change.

Thanks,
Daria

2022-03-16 13:45 UTC, dariavladykina commented on xml/bp_troubleshooting_dashboard.xml
> +   Follow the next steps to enable add the exception.
```suggestion
   Follow the next steps to add the exception.
```

2022-03-17 12:32 UTC, tbazant approved these changes
LGTM

2022-03-17 12:33 UTC, merged